# Generated by Django 3.2.4 on 2021-10-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subambiente',
            name='codigo_subambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionUsuariosApp.ambiente'),
        ),
        migrations.AlterField(
            model_name='subambiente',
            name='nombre_subambiente',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
